language: node_js
node_js:
  - lts/*

os:
  - linux
dist: focal

# branches:
#   only:
#     - main
#     - master

cache: npm

stages:
  - Checks

jobs:
  include:
    - stage: Checks
    - script: npm run check-docs
      name: Check Docs
